TRABALHO-2_DA: main.o menu.o grafo.o maxHeap.o
	g++ main.o menu.o grafo.o maxHeap.o -o trabalho2

main.o: main.cpp
	g++ -c main.cpp

menu.o: menu.cpp
	g++ -c menu.cpp

grafo.o: grafo.cpp
	g++ -c grafo.cpp

maxHeap.o: maxHeap.cpp
	g++ -c maxHeap.cpp

clean:
	rm *.o trabalho2